name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # ✅ Fixed indentation

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fix numpy and statsmodels compatibility  # ✅ Fixed indentation
      run: |
        pip install --upgrade pip
        pip install --upgrade numpy statsmodels
       
    - name: Run script
      run: |
        python Lasso_Ridge_reg.py  
    - name: Run pytest
      run: |
        pytest tests/ -v
       
